/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: 03a57bd1f2976119830836053136f8ce)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		TF2_UPDATE: KVNamespace;
		DISCORD_WEBHOOK_1: string;
	}
}
interface Env extends Cloudflare.Env {}
